version: 2

python:
    version: 3.6
    install:
        - method: pip
          path: .
          extra_requirements:
              - mkdocstrings
              - mkdocs-material

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

