site_name: Pydoautomator

theme: material

markdown_extensions:
    - admonition
    - codehilite

nav:
    - Getting Started: 'index.md'
    - API Reference: 'api_reference.md'

plugins:
    - mkdocstrings:
        default_handler: python
        watch:
            - pydoautomator