site_name: Pydoautomator


nav:
    - Getting Started: 'getting_started.md'
    - Automator: 'automator.md'

plugins:
    - mkdocstrings:
        default_handler: python
        watch:
            - pydoautomator