name: Test and report

on:
    push:
      branches:
        - develop
        - master
    pull_request:
      branches:
        - develop
        - master

jobs:
    buid:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.6'
            - name: Install dependencies
              run: |
                python --version
                python -m pip install poetry
                python -m pip install --upgrade pip
                poetry install
                poetry run python -m pytest --cov=./ --cov-report=xml tests/unit_tdd
            - name: Test with pytest
              run: |
                poetry run python -m pytest --cov=./ --cov-report=xml tests/unit_tdd
               
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
